### ISSUE TITLE
access data

### ISSUE THREAD

**Issue by PerspectivesLab** [bornabesic/subsampl#1]
Hi there !
could you provide the way to access the sample index from the ref buffer ?
thank you

**Comment by bornabesic** [comment]
Hi!
Can you clarify exactly which index you are referring to? Is it maybe the data from `point_to_voxels`?

https://github.com/bornabesic/subsampl/blob/0cc6efa5718a876e89e9c658f93b6d7ed55654f3/src/voxel.cpp#L95

**Comment by PerspectivesLab** [comment]
actually i figured out, i am using a source buffer and wanted to retrieve the source index, i found out this way :

```
auto* indices = voxel_grid_subsample_3d(&data[0], n, voxel_size);
for (auto it = indices->begin(); it != indices->end(); ++it ) { 
   auto element = *it;
   indexInSourceBuffer = element / 3; 
   ... // now use indexInSourceBuffer  to retrieve the source point
```
is this the correct way ? thank you

**Comment by bornabesic** [comment]
I assume the source buffer you are referring to is `data`.
If you are just trying to obtain the corresponding 3-dimensional vector from it using an index from `indices`, you should be multiplying the index by 3 instead of dividing it.

```cpp
auto *data_ptr = &data[0];
auto *indices_ptr = voxel_grid_subsample_3d(data_ptr, n, voxel_size);
const auto &indices = *indices_ptr;
for (const auto index : indices) {
    const auto offset = index * 3;
    const auto x = data_ptr[offset];
    const auto y = data_ptr[offset + 1];
    const auto z = data_ptr[offset + 2];
    // Do something with (x, y, z)
    // ...
}
```

**Comment by PerspectivesLab** [comment]
understood, thanks !
